### ISSUE TITLE
manylinux1 packaging

### ISSUE THREAD

**Issue by mzdaniel** [python-greenlet/greenlet#100]
Thank you so much for creating this awesome project!  I am the author of the
sphinxserve package that uses greenlet and gevent dependencies for concurrency.
Until recently linux users had to manually compile python bindings which
historically has been a major drawback. All that is changing with the
introduction of pep-513 and the superb work of the pypa/manylinux team who pushed the
issue and created the needed tooling including a docker image.

Do you think it would be possible to release manylinux1 greenlet wheels on pypi?

To make things as easy as possible here is a small shellscript that only 
depends on docker. It automatically downloads the manylinux image and create
the wheels on the current directory.

```
[admin@delphy tmp]$ cat build_greenlet.sh 
#!/usr/bin/env bash

CMD=$(cat << 'EOF'
cd /io
for version in 27 34 35; do
    /opt/python/cp${version}-cp${version}m/bin/pip wheel greenlet
    auditwheel repair greenlet*${version}*.whl
    rm greenlet*${version}*whl
done
mv wheelhouse/*whl .
rmdir wheelhouse
EOF
)

echo "$CMD" | docker run -i  -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /bin/bash
```

**Comment by snaury** [comment]
Thanks, this would certainly help with novice users that don't know about installing compilers and full python distributions. However from quick reading I already see that `${version}m` builds would not be enough, since almost all distributions need `${version}mu` nowadays. I will look into this later.

**Comment by mzdaniel** [comment]
Hi Alexey,
According to the gevent project the ones that matter the most are: cp27-cp27mu cp34-cp34m  cp35-cp35m. The following script generates all possible manylinux available on the docker image

```
#!/usr/bin/env bash

CMD=$(cat << 'EOF'
    versions=$(cd /opt/python; ls)

    cd /io
    for version in $versions; do
        /opt/python/${version}/bin/pip wheel greenlet
        auditwheel repair greenlet*${version}*.whl
        rm greenlet*${version}*whl
    done

    mv wheelhouse/*whl .
    rmdir wheelhouse
EOF
)

echo "$CMD" | docker run -i  -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /bin/bash
```

**Comment by mzdaniel** [comment]
Just in case, the above script was also tested using the docker toolbox  allowing to generate the manylinux python packages on OSX

**Comment by snaury** [comment]
Uploaded 0.4.9 manylinux wheels, thanks a lot for the tip!
