### ISSUE TITLE
greenlet.error: cannot switch to a different thread

### ISSUE THREAD

**Issue by bitnumus** [python-greenlet/greenlet#105]
Hi, I installed 0.4.9 via pip3 on ubuntu 16.04 and receive this error. The same package on 14.04 seems to work fine, not sure if that is related or not yet but its the only difference i can think of.

> File "/usr/local/lib/python3.4/dist-packages/eventlet/semaphore.py", line 145, in _do_acquire
>     waiter.switch()
> greenlet.error: cannot switch to a different thread

**Comment by snaury** [comment]
Thanks. I'll look into it later this week, but in the mean time, could you please show me the complete stack trace, provide a reproducible sample if possible, and tell me why you think greenlet is at fault and not some other library? For example, if you are actually calling into eventlet from a different thread than its hub, then the exception is correct: greenlet does not support switching between threads.

**Comment by bitnumus** [comment]
@snaury Thanks, you forced me to find that it was unrelated.

**Comment by dimaur-alpha** [comment]
> @snaury Thanks, you forced me to find that it was unrelated.

hi @shaun-ba  could you tell me how you resolved that issue
