### ISSUE TITLE
Using make-manylinux

### ISSUE THREAD

**Issue by amitsaha** [python-greenlet/greenlet#108]
How is the `make-manylinux` script supposed to be used? If I try to invoke it standalone, I get:

```
$ ./make-manylinux 
/bin/bash: /greenlet/make-manylinux: Permission denied

```

**Comment by snaury** [comment]
I'm using docker for mac and it works for me. What operating system are you using and where are your greenlet sources located?

**Comment by amitsaha** [comment]
I am on Linux and I am running from the root of a clone of this git repository.

**Comment by snaury** [comment]
Just tried it on a linux server and it worked, so I'm not sure what might be the problem with your docker setup. Let me know if you find out how to fix it.

**Comment by amitsaha** [comment]
Could be SELinux labels. I will check and update. Thanks for your help!

**Comment by amitsaha** [comment]
Yes, that was the issue, i need to do this:

```
diff --git a/make-manylinux b/make-manylinux
index a71f5a2..153f243 100755
--- a/make-manylinux
+++ b/make-manylinux
@@ -16,4 +16,4 @@ if [ -d /greenlet -a -d /opt/python ]; then
     exit 0
 fi
 
-docker run --rm -ti -v "$(pwd):/greenlet" quay.io/pypa/manylinux1_x86_64 /greenlet/$(basename $0)
+docker run --rm -ti -v "$(pwd):/greenlet:Z" quay.io/pypa/manylinux1_x86_64 /greenlet/$(basename $0)


```

**Comment by snaury** [comment]
Thanks!
