### ISSUE TITLE
Windows 64-bit DLL is broken

### ISSUE THREAD

**Issue by danielguardicore** [python-greenlet/greenlet#109]
Using greenlet version 0.4.10 on Python 2.7 64-bit on Windows (ActiveState distribution) gives the following bug:
`>>> import greenlet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.`

**Comment by danielguardicore** [comment]
The issue seems to have been solved in the latest version of Python 2.7 64-bit (2.7.10). Should probably add this dependency in the changelog or setup.py

**Comment by snaury** [comment]
Unfortunately it's impossible to add such a dependency to setup.py, besides if you are installing using setup.py there wouldn't be any problem. Python 2.7.4 has broken binary compability, so only binary packages require 2.7.4+.
