### ISSUE TITLE
something err

### ISSUE THREAD

**Issue by hyhlinux** [python-greenlet/greenlet#112]
from greenlet import greenlet

gr1 = None
gr2 = None

def test1():
    print 12
    print('test1', gr2)
    gr2.switch()
    print 34

def test2():
    print 56
    gr1.switch()
    print 78

def main():
    gr2 = greenlet(test2)
    gr1 = greenlet(test1)
    print(gr1, gr2)
    gr1.switch()

if __name__ == '__main__':
    main()

log:
(Traceback (most recent call last):
<greenlet.greenlet object at 0x0000000002977768>, <greenlet.greenlet object at 0x00000000029776D0>)
12
('test1', None)
            gr2.switch()
AttributeError: 'NoneType' object has no attribute 'switch'
[Finished in 0.2s with exit code 1]

window 7

**Comment by snaury** [comment]
You variables are local to the function, you should mark them global if you want it like that: https://docs.python.org/3/reference/simple_stmts.html#the-global-statement

**Comment by hyhlinux** [comment]
thank u
