### ISSUE TITLE
What is _stack_saved for?

### ISSUE THREAD

**Issue by tbodt** [python-greenlet/greenlet#115]
I can't really think of a good reason why I'd want to find out how much of the stack is saved on the heap. Why is this exposed?

**Comment by tbodt** [comment]
For science?

**Comment by snaury** [comment]
Denis Bilenko (gevent author) wanted this change, I guess it was for calculating how much memory is used for saved stacks. I can't seem to find if anyone is using it, but I guess you can emulate it easily with something like `started && !current ? self->stack_size : 0`.

**Comment by tbodt** [comment]
libcoro always allocates the same amount for a stack by default, so I could return that. I guess if I add an option for specifying the amount of stack space you want on a greenlet I could return that, but I don't think that option would be very useful.

**Comment by tbodt** [comment]
`started && !current` doesn't quite make this test pass, it fails on the last assertion:

```python
def test_stack_saved(self):
    main = greenlet.getcurrent()
    self.assertEqual(main._stack_saved, 0)

    def func():
        main.switch(main._stack_saved)

    g = greenlet.greenlet(func)
    x = g.switch()
    assert x > 0, x
    assert g._stack_saved > 0, g._stack_saved
    g.switch()
```

**Comment by tbodt** [comment]
`active && !current` does, though.
