### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by fornwall** [python-greenlet/greenlet#116]
Is it possible to create a new release to get https://github.com/python-greenlet/greenlet/commit/8c8c68279d2e2588ef1078d38eba3429cc4a642d included? Several [Termux](https://termux.com/) users are hit by this when trying to install things depending on greenlet.

**Comment by snaury** [comment]
Sure, I'll try doing it this weekend.

**Comment by snaury** [comment]
Version 0.4.11 has been released.
