### ISSUE TITLE
Doesn't compile with Python 3.7 due to tstate changes

### ISSUE THREAD

**Issue by nascheme** [python-greenlet/greenlet#123]
[greenlet-tstate.txt](https://github.com/python-greenlet/greenlet/files/1525020/greenlet-tstate.txt)

The patch is too simple, will need to have an ifdef with the Python version to switch between the old tstate struct and the new one with exc_state.

**Comment by snaury** [comment]
Is it going to land in alpha3? I just downloaded alpha2 and there's no `exc_state` in `PyThreadState`.

**Comment by snaury** [comment]
I can't find it in mercurial either: https://hg.python.org/cpython/file/4243df51fe43/Include/pystate.h :-/

**Comment by snaury** [comment]
Tracked it to python/cpython#1773. I think I'm going to wait until alpha3 is released, so I could use `PY_VERSION_HEX >= 0x030700A3` as a guard.

**Comment by nascheme** [comment]
The change is in git commit ae3087c6382011c47db82fea4d05f8bbf514265d.  
Oct 22.

**Comment by nascheme** [comment]
cython uses #if PY_VERSION_HEX >= 0x030700A2.

See <https://github.com/cython/cython/commit/8ad16fc871be075f889d5e7c2892db3e4c8ce978> as an example.  There are a few other places cython accesses  the exc_state struct.

**Comment by nedbat** [comment]
When can we expect a new release with this fix?

**Comment by snaury** [comment]
Python 3.7 is not released yet, not even a beta or a release candidate, why would you expect me to make a release? I don't follow python news though, so would you please remind me when a release candidate for 3.7 is finally release? I think that would be a good time for the new greenlet release, as possibility for further breaking changes would be minimal.

**Comment by snaury** [comment]
Since you are testing against alpha, can't you just install a dev version of greenlet from source? Anyway, making a release is a lot of manual work with many opportunities to make a mistake, I would prefer avoiding it as much as possible.

**Comment by nedbat** [comment]
I can do that, and it works.  But it means I have to install cython and choose a random sha from GitHub. It's slow and forces me to make some arbitrary decisions.

**Comment by snaury** [comment]
> But it means I have to install cython

Why would you need that? Greenlet doesn't use nor depend on cython at this time.

> and choose a random sha

You could also just use master, the link would be `https://github.com/python-greenlet/greenlet/archive/master.zip`

**Comment by nedbat** [comment]
Oops, it's gevent that needs Cython.

**Comment by snaury** [comment]
Looks like beta1 is finally out, so I just released greenlet 0.4.13.

**Comment by wwqgtxx** [comment]
the Python3.7 was released, would the py37 wheels add to pypi.org?

**Comment by snaury** [comment]
Thanks, I just built Linux wheels for 3.7, unfortunately for Windows it looks like AppVeyor changed something and build scripts no longer work, so no Windows builds at the moment. :-/

**Comment by snaury** [comment]
Ah, looks like neither travis nor appveyor have python 3.7 yet anyway.
