### ISSUE TITLE
Eventlet crashes with Python 3.7

### ISSUE THREAD

**Issue by hroncok** [python-greenlet/greenlet#131]
This is a cross reference bug for:

 * https://github.com/eventlet/eventlet/issues/475
 * https://bugs.python.org/issue33996

greenlet only reproducer: [dagpool_test.py](https://bugs.python.org/file47658/dagpool_test.py)

**Comment by markshannon** [comment]
I've attempted to triage https://bugs.python.org/issue33996 without success. 
https://github.com/python-greenlet/greenlet/commit/780a12b51fcef9adcc4f2c9a4cc5b05c2d652ba4
seems incorrect. Greenlets should not hold the exception triple.
Either they should hold a pointer to the topmost coroutine/generator, or compute it from the frame.

**Comment by snaury** [comment]
Greenlet needed to save/restore exception state because many greenlets share a thread, and when greenlets switch their exception state must switch with them. I thought 3.7 merely moved exception state to an inner struct, did something fundamental change instead?

**Comment by vstinner** [comment]
I wrote a fix: PR #132.

**Comment by vstinner** [comment]
> I thought 3.7 merely moved exception state to an inner struct, did something fundamental change instead?

3 fields (exc_type, exc_value, exc_traceback) moved into a structure, but a new field previous_item has been added as well. My PR modifies greenlet to also handle this field.

**Comment by temoto** [comment]
Thank you very much, @vstinner you are hero.
