### ISSUE TITLE
Undefined symbols for Linux wheels deployed to WSL

### ISSUE THREAD

**Issue by televi** [python-greenlet/greenlet#138]
### Background
For a variety of reasons, we are required to only deploy wheels we build from source.  To facilitate this, we simply build the wheels we need in a Linux system (CentOS 7) and store them in a private PyPi repo so we can consume them easily later.

### Problem
We've begun using Linux via the Windows 10 WSL (Windows Subsystem for Linux) and it works extremely well (no more cygwin).  However, when we install the greenlet wheel we built in CentOS into Ubuntu 18.04 WSL, we get undefined symbol errors when we try to use it.

The specific symbols in the greenlet.foo.so file are AnnotateIgnoreReadsBegin and AnnotateIgnoreReadsEnd.  Both of those seem to be controlled from /usr/include/python*/dynamic_annotations.h via a #ifdef for DYNAMIC_ANNOTATIONS_ENABLED.  I think this is related to [PEP-3107](https://www.python.org/dev/peps/pep-3107/), [PEP-483](https://www.python.org/dev/peps/pep-0483/), and [PIP-484](https://www.python.org/dev/peps/pep-0484/) but I could be totally wrong about that.

In any case, if I build the greenlet wheel directly in Ubuntu 18.04 WSL, those symbols are not included in the greenlet.*.so file.  The wheel built in WSL and in CentOS show themselves to be for an arch of linux, (greenlet-0.4.14-foo-bar-linux_x86_64.whl) so there's nothing to distinguish one build from the other beyond the actual symbols that appear in the .so file.

What I can't seem to find is why/where DYNAMIC_ANNOTATIONS_ENABLED gets flipped between one system and the other.  Both are running the same versions of python (3.4 but I've reproduced it on 3.5 as well using the same systems).  I didn't see anything in the greenlet code that would flip that but this is well beyond my normal python experience.

### The Ask
I simply don't know where to look next - I'm not even sure where or with whom the problem lies (me, greenlet, WSL, something else?).  A google search was unhelpful - lots of people seeing similar problems with no one actually saying how to solve it beyond "just install from source".

Is this something that you've seen?  Do you have any pointers on where I can look or what I can try so that I can have one wheel that works in both a "normal" Linux environment as well as a WSL Linux environment?

### Workaround
For now, I've simply created a constraint.txt file for our project that we can use in the WSL environment (the constraint is to never install greenlet from a wheel - only source installs) and that works but it also means people aren't testing locally against what we ship so is less than ideal.

**Comment by snaury** [comment]
Hi, thank you for the report, but I'm not sure if greenlet can do anything about this, since wheels are built using official manylinux docker images. Perhaps it would be better to create an issue in https://github.com/pypa/manylinux

**Comment by televi** [comment]
Just to make sure I understand, when I build a greenlet wheel on my system, greenlet's setup.py will (at some point) grab a pypa manylinux docker image, pull it to my system, and use that as its base for determining which symbols to use?  That would be pretty cool but totally new to me.

**Comment by snaury** [comment]
> when I build a greenlet wheel on my system, greenlet's setup.py will (at some point) grab a pypa manylinux docker image

No, of course not. When you build greenlet locally it will use whatever Python you're using, and those wheels may not be suitable for manylinux releases. When I prepare releases however, I build wheels using a manylinux docker image and later upload them to pypi.

**Comment by televi** [comment]
Hmm...  OK - I still don't know where this is going south, but it is pretty clear that it isn't anything in greenlet at this point.  I have no idea where DYNAMIC_ANNOTATIONS_ENABLED is being set/unset but from what I can see greenlet just inherits it (from somewhere).  I'll keep looking around and if anything comes up that points back here I'll open a separate issue with the details.

**Comment by snaury** [comment]
Oh, I've just realized that you had issue with wheels you built yourself, not wheels uploaded on pypi. Sorry for the confusion, if you need to build manylinux wheels look at the `make-manylinux` script in the greenlet repo, it's what I'm using to make releases.
