### ISSUE TITLE
Is there a sys.excepthook alternative for greenlets ?

### ISSUE THREAD

**Issue by tzickel** [python-greenlet/greenlet#140]
In the end, I want any unhandled exception inside a grenlet to bubble up to my custom logger instead of being printed to stderr. In regular Python we have:

https://docs.python.org/3/library/sys.html#sys.excepthook

What are my options in greenlets / gevent ?

**Comment by snaury** [comment]
Greenlet rethrows exceptions in a chain from children to parents and never prints them. What you are referring to is a feature of gevent, here's the function with relevant docstring:

https://github.com/gevent/gevent/blob/7b6af6fa3634dd03910678ac07213727d8c88fda/src/gevent/hub.py#L454
