### ISSUE TITLE
When running in main(), NameError appears and the global variable cannot be read(lates version)，whether it is windows or linux

### ISSUE THREAD

**Issue by perloliu** [python-greenlet/greenlet#141]
# When running in main(), NameError appears and the global variable cannot be read(greenlet is the lates version)，whether it is windows or linux.

### 
> C:\Users\57018\Desktop\nothing\venv\Include>python demo_greenlet.py
> -----test1-----
> Traceback (most recent call last):
>   File "demo_greenlet.py", line 26, in <module>
>     main()
>   File "demo_greenlet.py", line 23, in main
>     g1.switch()
>   File "demo_greenlet.py", line 8, in test1
>     g2.switch()
> NameError: name 'g2' is not defined

```
from greenlet import greenlet
import time


def test1():
    while True:
        print("-----test1-----")
        g2.switch()
        time.sleep(1)


def test2():
    while True:
        print("-----test2-----")
        g1.switch()
        time.sleep(1)


def main():
    g1 = greenlet(test1)
    g2 = greenlet(test2)
    
    g1.switch()

if __name__ == "__main__":
    main()
```
###

> C:\Users\57018\Desktop\nothing\venv\Include>python demo_greenlet.py
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----
> -----test1-----
> -----test2-----

```
from greenlet import greenlet
import time


def test1():
    while True:
        print("-----test1-----")
        g2.switch()
        time.sleep(1)


def test2():
    while True:
        print("-----test2-----")
        g1.switch()
        time.sleep(1)


g1 = greenlet(test1)
g2 = greenlet(test2)
    
g1.switch()
```

## So I want to know why, or if there is a bug, or if there is a problem with my usage, please advise, thank you.

**Comment by perloliu** [comment]
The same problem with linux.

**Comment by snaury** [comment]
This is normal Python behavior. I would advise to seek support in python-related mailing lists, chats, or on stackoverflow.

**Comment by perloliu** [comment]
> 这是正常的Python行为。我建议在python相关的邮件列表，聊天或stackoverflow中寻求支持。

Thank you very much. I discovered this in the near future.
