### ISSUE TITLE
Support wheel package for Python 3.8

### ISSUE THREAD

**Issue by TihonV** [python-greenlet/greenlet#151]
Could you update wheel at PyPI for 3.8?
That's allow to use `gevent` with `python:3.8-slim` based docker-containers.

**Comment by snaury** [comment]
Linux wheels for python 3.8 uploaded, built from `0.4.15` tag.

**Comment by snaury** [comment]
Windows wheels for python 3.8 uploaded too, built from 066ec7270eed218511497ac48cb7775f4d72fdd8 (`0.4.15-py38-win` tag, thanks to @Bengt for appveyor patches!)
