### ISSUE TITLE
Question File Level Objects

### ISSUE THREAD

**Issue by Mradr** [python-greenlet/greenlet#168]
Does Greenlets do anything special with loading large files IO? For example, while the system is gathering the data - does it yield to other greenlets to continue running?

**Comment by jamadden** [comment]
greenlet knows nothing about IO. Using a standard file (e.g., as returned by `open`) may drop the GIL, but it doesn't let greenlets switch — the standard library isn't greenlet aware in any way. So another native thread might be able to run, but greenlets is the same native thread will be blocked. (Recall that this library never implicitly switches greenlets except when one exits; all switches between greenlets require your code to run `glet.switch()` or `glet.throw()`.) 

To let greenlets run while doing IO, you'll need a higher level framework like [gevent's FileObject](http://www.gevent.org/api/gevent.fileobject.html), or you'll need to roll your own IO system that is greenlet aware.
