### ISSUE TITLE
Segfaults with 0.4.17 release

### ISSUE THREAD

**Issue by robbrit** [python-greenlet/greenlet#180]
When using [Locust](https://locust.io/) (built on top of gevent) I get a greenlet error message followed by a segmentation fault upon startup:

```
/usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/local/lib/python3.7/site-packages/locust/util/deprecation.py:17: DeprecationWarning: Usage of User.task_set is deprecated since version 1.0. Set the tasks attribute instead (tasks = [UserBehaviour])
  DeprecationWarning,
[2020-09-23 22:53:24,332] 2887b8bc47e8/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2020-09-23 22:53:24,339] 2887b8bc47e8/INFO/locust.main: Starting Locust 1.2.3
Segmentation fault (core dumped)
```

I believe this to be a greenlet problem because greenlet 0.4.17 was just released yesterday, and rolling back to 0.4.16 fixes the problem:

    pip install greenlet==0.4.16

**Comment by jamadden** [comment]
Please see #178 and install a newer version of gevent or an older greenlet.

**Comment by robbrit** [comment]
Thanks, I bet you guys have been getting spammed all day :)

FWIW using the latest gevent still got the seg fault, only fix was to roll back greenlet.

**Comment by jamadden** [comment]
Ok, then perhaps locust also has an ABI dependency. I assumed gevent was the only ABI dependency. Thanks for the report! Do you have a github or other link to file an issue with them?

**Comment by robbrit** [comment]
Trying to reproduce on a fresh virtualenv and can't do it. Must have been some sort of version mismatch somewhere, so just ignore me for now.
