### ISSUE TITLE
RuntimeWarning on gunicorn

### ISSUE THREAD

**Issue by MuslimBeibytuly** [python-greenlet/greenlet#182]
:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
when running gunicorn with gevent - python 3.8.5-alpine3.12

**Comment by jamadden** [comment]
You'll need to upgrade gevent (or downgrade greenlet) or you're likely going to experience crashes. Please see #178
