### ISSUE TITLE
Move to the src/ layout

### ISSUE THREAD

**Issue by jamadden** [python-greenlet/greenlet#184]
This has some advantages. One that I've come to very much appreciate is separating out the build-in-place directories from the (usual) working directory. This should obviate some of the need for workarounds like https://github.com/python-greenlet/greenlet/blob/71ecaa8188894dccdf35351614e65f07752c2414/run-tests.py#L44-L47

I also intend to distribute (and install) the source and tests in the binary distributions; they are small, but provide benefit for end users trying to debug issues, or just understand how greenlet works without having to go to github. I don't see any penalties for that besides a negligible size increase.

**Comment by snaury** [comment]
Just in case, make sure you update paths in the `LICENSE` file, so files that are under PSF license (most of greenlet is MIT, but files that came from stackless are PSF) are correctly marked.
