### ISSUE TITLE
Stop trying to use distutils and test_suite=

### ISSUE THREAD

**Issue by jamadden** [python-greenlet/greenlet#185]
Distutils has been deprecated in the standard library. It is now vendored into setuptools.

Likewise, stop trying to set a `test_suite` in the setuptools arguments. That's also deprecated.

**Comment by jamadden** [comment]
Fixed by #208

**Comment by thewizof6** [comment]
Is this fix to be released with v3.2.5?
I ran into https://github.com/python-greenlet/greenlet/issues/185 in v3.2.4.
