### ISSUE TITLE
Drop support for long obsolete Python versions

### ISSUE THREAD

**Issue by jamadden** [python-greenlet/greenlet#186]
The classifiers claim to support 2.4, 2.5, 2.6, 3.0, 3.1, 3.2, 3.3, and 3.4. Some or all of those are tested on CI. But 2.4, 2.5, 2.6, 3.0, 3.1, 3.2, and 3.3 are long obsolete. 3.4 is also out of support, though perhaps not obsolete.

**Comment by jamadden** [comment]
Only 2.6 is still tested on CI, but the classifiers claim support for 2.4 and 2.5.

**Comment by hugovk** [comment]
Here's the pip installs for greenlet from PyPI for 1-29 September 2020:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  37.66% | 1,050,436 |
| 3.6      |  23.77% |   662,952 |
| 2.7      |  20.08% |   560,009 |
| 3.8      |  14.51% |   404,891 |
| 3.5      |   2.40% |    66,937 |
| null     |   1.14% |    31,717 |
| 3.4      |   0.37% |    10,428 |
| 3.9      |   0.07% |     1,825 |
| 3.10     |   0.01% |       154 |
| 3.3      |   0.00% |        87 |
| 2.6      |   0.00% |        80 |
| 2.4      |   0.00% |         4 |
| 2.5      |   0.00% |         3 |
| Total    |         | 2,789,523 |

Source: `pip install -U pypistats && pypistats python_minor greenlet --last-month`

**Comment by jamadden** [comment]
Thank you for the information! I hadn't gotten that far yet.

We'll make sure to include the proper `python_requires` metadata to help prevent unsupported interpreters from installing mismatched versions. That said, the most ancient of those versions don't support a modern toolchain that understands that metadata. We'll also bump the major version so at least a simple version pin like `< 1' should work.
