### ISSUE TITLE
compile error solaris 10 x86 32bit

### ISSUE THREAD

**Issue by chassing** [python-greenlet/greenlet#19]
Hi,

i try to install greenlet 0.4.0 on solaris 5.10 x86 with a 32bit python 2.6 (from opencsw.org) and i get the following compile error :(

$ CC=/opt/sunstudio_12/bin/cc /opt/csw/bin/python2.6 setup.py build
running build
running build_ext
building 'greenlet' extension
creating build/temp.solaris-2.10-i86pc-2.6
/opt/sunstudio_12/bin/cc -xO3 -m32 -xarch=pentium_pro -xchip=pentium_pro -OPT:Olimit=0 -xO3 -m32 -xarch=pentium_pro -xchip=pentium_pro -DNDEBUG -O -Kpic -I/opt/csw/include/python2.6 -c greenlet.c -o build/temp.solaris-2.10-i86pc-2.6/greenlet.o
cc: Warning: illegal option -OPT:Olimit=0
"greenlet.c", line 420: #error: "greenlet needs to be ported to this platform, or teached how to detect your compiler properly."
cc: acomp failed for greenlet.c
error: command '/opt/sunstudio_12/bin/cc' failed with exit status 2

$ file /opt/csw/bin/python2.6
/opt/csw/bin/python2.6: ELF 32-bit LSB executable 80386 Version 1 [FPU], dynamically linked, stripped

$ uname -a
SunOS vihuc839 5.10 Generic_147441-10 i86pc i386 i86pc

notes:
- /opt/csw/bin/python2.6 is opencsw installed python2.6 
- /opt/sunstudio_12/bin/cc is sunstudio compiler

any idea?

thanks, 
chris

**Comment by jamadden** [comment]
Closing since it's believed fixed and there's been no response from the OP in 6 years.
