### ISSUE TITLE
PyPi needs Windows wheels for Python 3.9

### ISSUE THREAD

**Issue by RussellJQA** [python-greenlet/greenlet#200]
Greenlet's PyPi page (at https://pypi.org/project/greenlet/) lists "Python :: 3.9" among its supported programming languages. But although its "Download files" page has a Python 3.9 wheel for Linux, it doesn't have any for Windows.

As a result, when I tried to install Microsoft's Playwright for Python (https://pypi.org/project/playwright/), I got a:

```
c:\python39\include\pyconfig.h(201): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit code 2
```

error when it tried to install greenlet. Here's the full error output:

[Output from pip install playwright (after first pip-installing wheel).txt](https://github.com/python-greenlet/greenlet/files/5442513/Output.from.pip.install.playwright.after.first.pip-installing.wheel.txt)

Could you please add Windows wheels for Python 3.9 to PyPi?

Thank you.

**Comment by fabiorfreitas** [comment]
I'm facing the exact same issue. There isn't a wheel available to Windows on Python 3.9 and I can't seem to build one myself via `pip install greenlet`

**Comment by fabiorfreitas** [comment]
Update: installing Visual C++ Build Tools (with all optional packages) allowed me to build the wheel.

**Comment by davegoopot** [comment]
Top work! How is this published to PyPi?

**Comment by fabiorfreitas** [comment]
Beats me. I haven't yet put time to properly learn Python and all things related, I just tried to read through the error message and noticed it said something like "failed to obtain wheel from PyPi, trying to build" and then tried to get that working ¯\_(ツ)_/¯

**Comment by davegoopot** [comment]
Anyone from the project team able to comment on how we can get a python 3.9 wheel for windows up on PyPi? I'm happy to help if I can.

**Comment by jamadden** [comment]
Wheels for 1.0a1 are now available on PyPI. (I'm not able to publish wheels for an older version, but 1.0a1 should be binary and source compatible with 0.4.17.)
