### ISSUE TITLE
Add support for Windows on ARM64

### ISSUE THREAD

**Issue by ader1990** [python-greenlet/greenlet#220]
Hello,

I am trying to use greenlet with Python 3.8 / 3.9 on Windows ARM64, but there is a compilation issue when I try building it using VS Studio 2017 / 2019:

```
src/greenlet/greenlet.c(353): fatal error C1189: #error:          "greenlet needs to be ported to this platform, or taught how to detect your compiler properly."
```

It seems there has to be a special switch implementation here for ARM64, but currently I do not know how to tackle it:
https://github.com/python-greenlet/greenlet/blob/master/src/greenlet/slp_platformselect.h#L8

Can anyone help me with some pointers for the win32 ARM64 switch?

Thank you,
Adrian

**Comment by jamadden** [comment]
Fixed by #271
