### ISSUE TITLE
Greenlet fails to build with python3.9 on OSX 11.1

### ISSUE THREAD

**Issue by willdoescode** [python-greenlet/greenlet#223]
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hm/ppcgc66x2rj_th2z7x61qxxc0000gn/T/pip-install-gqef_b2x/greenlet_c3e199fba4294ee695011e401445e33f/setup.py'"'"'; __file__='"'"'/private/var/folders/hm/ppcgc66x2rj_th2z7x61qxxc0000gn/T/pip-install-gqef_b2x/greenlet_c3e199fba4294ee695011e401445e33f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hm/ppcgc66x2rj_th2z7x61qxxc0000gn/T/pip-record-vj_jwnky/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/greenlet Check the logs for full command output.

**Comment by jamadden** [comment]
You haven't included the actual error (the instructions on how to find it are right there at the end), and what you have pasted is unreadable.

As it is, I'm going to guess that this is a variation on https://github.com/gevent/gevent/issues/1707, meaning that you need updated packaging tools. Unless you can provide more information indicating it's something else, there's nothing I can do about that.

**Comment by willdoescode** [comment]
The greenlet install worked with python3.8 just not 3.9. It is probably an issue with my machine.

**Comment by jamadden** [comment]
If you can include the actual error, I may be able to suggest something more specific.

**Comment by willdoescode** [comment]
I couldn't locate the log file at all. Do you know where it would be?

**Comment by jamadden** [comment]
I don't know what command you ran, but usually errors that pip encounters when running `setup.py` after you type `pip install some_project` are on the console just above the line you included originally; check there. It might help to make sure you haven't asked pip to be quiet with the `-q` switch, and it might help to explicitly ask pip to be verbose with the `-v` switch, e.g., `pip install -v greenlet` (or `python/to/python3.9 -mpip install -v greenlet` if that's how you're invoking pip).(Be warned, `-v` produces lots of output to sift through).

If you're in some GUI IDE or something, I don't know where it would keep log files. I suggest running the install directly from the command line, probably into a virtual environment. This just worked for me on macOS catalina using python3.9 from MacPorts:

```console
$ /opt/local/bin/python3.9 -mvenv venv
$ venv/bin/python -m pip install -v greenlet
…
  Using cached greenlet-1.0a1-cp39-cp39-macosx_10_15_x86_64.whl (86 kB)
  Added greenlet from https://files.pythonhosted.org/packages/a7/99/7a38a3e964785389615f48b266ad3a88e1969ba604403f93fbd5e5bebb21/greenlet-1.0a1-cp39-cp39-macosx_10_15_x86_64.whl#sha256=9249796c5ddc277be194c9da9e0a3e9bf3d11f6e2497f13f2ee65ac38a824714 to build tracker '/private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-req-tracker-jgvk4_1n'
  Removed greenlet from https://files.pythonhosted.org/packages/a7/99/7a38a3e964785389615f48b266ad3a88e1969ba604403f93fbd5e5bebb21/greenlet-1.0a1-cp39-cp39-macosx_10_15_x86_64.whl#sha256=9249796c5ddc277be194c9da9e0a3e9bf3d11f6e2497f13f2ee65ac38a824714 from build tracker '/private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-req-tracker-jgvk4_1n'
Installing collected packages: greenlet

Successfully installed greenlet-1.0a1
…
```

**Comment by willdoescode** [comment]
![Screen Shot 2020-12-02 at 14 51 17](https://user-images.githubusercontent.com/53620720/100941095-e7ed3080-34ad-11eb-807d-f8d7583dbe4f.png)
![Screen Shot 2020-12-02 at 14 51 27](https://user-images.githubusercontent.com/53620720/100941104-ea4f8a80-34ad-11eb-98d4-d4331d2822ce.png)

**Comment by jamadden** [comment]
Please always post the actual text, not a picture of the text.

**Comment by jamadden** [comment]
If I can read those pictures correctly, this seems to be some internal issue in the unmaintained `distutils` shipped with CPython. That's only used by greenlet 0.4.x; newer versions use setuptools directly. So you could try installing 1.0a1. You'll need to be explicit (`pip install 'greenlet>=1.0a1`) or use the `--pre` switch.
