### ISSUE TITLE
compilation terminated.     error: command 'i686-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by mikegrep** [python-greenlet/greenlet#225]
I am trying to install on Ubutntu 18.04 with python 3.7 also with python 3.6.5 I recive same error after tying to install with pip How can I fix it.Thanx

  **In file included from greenlet.c:5:0:
    greenlet.h:8:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'i686-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-thx0zjpv/greenlet_224e3902c8a948bba84ad67c323661d3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-thx0zjpv/greenlet_224e3902c8a948bba84ad67c323661d3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qhthvn64/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pc/.local/include/python3.7m/greenlet Check the logs for full command output.**

**Comment by jamadden** [comment]
You need to be able to build Python extensions written in C. In addition to the compiler, you must also have the Python development headers installed. If you're using a version of Python installed from your operating system's package installer, sometimes that means you must also install a separate package such as "python-dev" or something. For example, on one Fedora system, that meant you needed to "yum install python3-devel". I don't know what it is on your system, you'll have to look.

Good luck!

**Comment by mikegrep** [comment]
Reading state information... Done
python3-dev is already the newest version (3.6.7-1~18.04).I have installed Thanks anyway
