### ISSUE TITLE
Broken on ppc64le

### ISSUE THREAD

**Issue by jeremyfreudberg** [python-greenlet/greenlet#230]
Greenlet is unusable out of the box on ppc64le. The wheel is not built properly.

```
[root@jeremy ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.3 (Ootpa)
[root@jeremy ~]# arch
ppc64le
[root@jeremy ~]# virtualenv genv
Using base prefix '/usr'
New python executable in /root/genv/bin/python3.6
Also creating executable in /root/genv/bin/python
Installing setuptools, pip, wheel...done.
[root@jeremy ~]# source genv/bin/activate
(genv) [root@jeremy ~]# pip install greenlet
Collecting greenlet
  Downloading greenlet-1.0.0-cp36-cp36m-manylinux2014_ppc64le.whl (160 kB)
     |████████████████████████████████| 160 kB 663 kB/s 
Installing collected packages: greenlet
Successfully installed greenlet-1.0.0
(genv) [root@jeremy ~]# python -c 'import greenlet'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/genv/lib/python3.6/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ModuleNotFoundError: No module named 'greenlet._greenlet'
(genv) [root@jeremy ~]# cp genv/lib/python3.6/site-packages/greenlet/_greenlet.cpython-36m-powerpc64le-linux-gnu.so genv/lib/python3.6/site-packages/greenlet/_greenlet.so
(genv) [root@jeremy ~]# python -c 'import greenlet'
(genv) [root@jeremy ~]# echo $?
0

**Comment by jamadden** [comment]
Tests pass, so I don’t know what the problem might be. This is an incredibly niche platform (outdated python on rare hardware) so I can only say that help is welcome!

**Comment by jeremyfreudberg** [comment]
Thanks for the hint. I just tried with python 3.8 and greenlet appears to function without a workaround.
I'll see what I can figure out

**Comment by jeremyfreudberg** [comment]
Er no, just kididng. It doesn't work on python 3.8 either.

**Comment by jeremyfreudberg** [comment]
Ok, I understand what's going on now.
When installing greenlet with the pypi-provided wheel, the object file is called _greenlet.cpython-36m-powerpc64le-linux-gnu.so
When building greenlet locally, the object file is called _greenlet.cpython-36m-ppc64le-linux-gnu.so

This ppc64le vs powerpc64le matter is not specific to greenlet. See https://github.com/pypa/manylinux/issues/687 for further discussion

**Comment by jamadden** [comment]
Thanks for the investigation!
