### ISSUE TITLE
No longer able to install in python:alpine docker container

### ISSUE THREAD

**Issue by tarrenj** [python-greenlet/greenlet#232]
Hello!

Late last week my containers were building fine, but they're no longer building. I've been able to reproduce the build error with `docker run -it python:alpine pip3 install greenlet`

It looks like the failing line is: `    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.9 -c src/greenlet/greenlet.c -o build/temp.linux-x86_64-3.9/src/greenlet/greenlet.o` resulting in `error: command 'gcc' failed: No such file or directory`

[sprunge link of the full build error](http://sprunge.us/AGvnNL)

**Comment by jamadden** [comment]
There have been no changes to greenlet since the last release in January, so if something changed I don't think it is on greenlet's part.

It's not possible to distribute compiled, native, binary wheels on PyPI for Alpine Linux (in general, any distribution not based on glibc), so people using those platforms together with native Python extensions (typically written in C, like greenlet is) will need to be sure their platform has a functioning compiler toolchain, or arrange to build and host binary wheels somewhere else. In this case, it looks like the container is missing the basic compiler toolchain (gcc).

**Comment by tarrenj** [comment]
Thanks for the info. I'm actually installing the cryptography module into the same container, so I've added the following line: `apk --no-cache add gcc musl-dev libffi-dev openssl-dev python3-dev` and am still getting the same issue.  You can reproduce that with this dockerfile:

```
from python:alpine
RUN apk --no-cache add gcc musl-dev libffi-dev openssl-dev python3-dev
RUN pip3 install greenlet
```

I'll start looking into what changed in the latest version of the container now.

**Comment by tarrenj** [comment]
Actually, I'm going to close this out since the change wasn't in greenlet.  Thanks!

**Comment by pbhoiwala** [comment]
@tarrenj Have you been able to figure out what is causing this issue? I am running into the same error. I am not sure which one of my dependencies is using greenlet but I see this error
```
 Building wheel for greenlet (setup.py): started
  Building wheel for greenlet (setup.py): finished with status 'error'
[91m  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ltznfszi/greenlet_8f396f618d3448d3b7391fca38d47f87/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ltznfszi/greenlet_8f396f618d3448d3b7391fca38d47f87/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-271j_lm4
       cwd: /tmp/pip-install-ltznfszi/greenlet_8f396f618d3448d3b7391fca38d47f87/
   ```
and then this
       
```
        building 'greenlet.tests._test_extension_cpp' extension
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/greenlet/ -I/usr/local/include/python3.8 -c src/greenlet/tests/_test_extension_cpp.cpp -o build/temp.linux-x86_64-3.8/src/greenlet/tests/_test_extension_cpp.o
  gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ```
  
I'd appreciate any help

**Comment by pbhoiwala** [comment]
@tarrenj Thank you very much for the help. I appreciate it.

**Comment by tarrenj** [comment]
Does anyone know if building on the latest Alpine image is successful again?

**Comment by mholubinka1** [comment]
@tarrenj had the same issue installing greenlet as a dependency for bcrypt with flask. Adding g++ as part of the compiler toolchain fixed it.

**Comment by tarrenj** [comment]
@mholubinka1 Thanks for the additional information!

**Comment by futurerahul** [comment]
@mholubinka1 how did you add g++ compiler toolchain?

**Comment by dejurin** [comment]
> @mholubinka1 how did you add g++ compiler toolchain?

RUN apk add build-base

**Comment by Aatmjeet** [comment]
@dejurin  thanks mate, it worked for me!
