### ISSUE TITLE
No wheel for M1 macOS on pypi

### ISSUE THREAD

**Issue by rkhwaja** [python-greenlet/greenlet#234]

**Comment by jamadden** [comment]
Currently it's not possible to build and upload such wheels from our CI system, so they won't be available until the CI can make that update.

**Comment by redbmk** [comment]
Since this is still an issue shouldn't it be reopened?

**Comment by wookayin** [comment]
M1 arm64 build is now possible in Github Actions CI, so it'd be great if we can add M1 wheels in version 2.0.

**Comment by mtvx** [comment]
@jamadden Please re-open this ticket? Should be closed once the binaries are available... assuming that you plan to publish them once possible (now)?

**Comment by jamadden** [comment]
I have no plans to do so. Binary wheels are a convenience only and not my priority in the limited amount of time I can spend on projects. I would look at PRs that added them, of course.

**Comment by oceansofvectors** [comment]
Why is it that time and time again open source projects that so many things rely on are run by some single bitter lonely engineer.

**Comment by oceansofvectors** [comment]
Hopefully someone replaces greenlet soon, perhaps chatGPT can increase that process.
