### ISSUE TITLE
Syntax Error on Parrot

### ISSUE THREAD

**Issue by leomiglio02** [python-greenlet/greenlet#235]
greenlet version: 0.4.17-1+b1 preinstalled in parrotOS
Python version: "Python 3.9.2-1 preinstalled on parrotOS"
Operating System: "ParrotOS parrot5.7.0-2parrot2-amd64 (Debian Linux 5.7.10) x86_64"

##Description:

I was updating from apt and get configuration error caused by syntax error on /var/lib/dpkg/info/python3-greenlet.postinst

Setting up python3-greenlet (0.4.17-1+b)
/var/lib/dpkg/info/python3-greenlet.postinst: 1: Syntax error: ")" unexpected
dpkg: error processing package python3-greenlet (--configure):
installed python3-greenlet package post-installation script subprocess return
ed error exit status 2
Errors were encountered while processing:
python3-greenlet

##What I've run:

sudo dpkg --configure python3-greenlet

**Comment by jamadden** [comment]
I can almost quote the reply I gave in https://github.com/gevent/gevent/issues/1782#issuecomment-809285515

Although this project *is* greenlet, it still has nothing to do with the packaging for Debian. You'll need to open an issue with your operating system's package maintainers.
