### ISSUE TITLE
Static type checking

### ISSUE THREAD

**Issue by Changaco** [python-greenlet/greenlet#244]
It looks like no [stub file](https://mypy.readthedocs.io/en/stable/stubs.html) has been written for this library yet. Would a pull request to add the type hints directly in this repository be merged, or would you prefer them to be in a separate `types-greenlet` package?

**Comment by jamadden** [comment]
Thank you for your interest! I currently have no desire to try to maintain any typing information in this C-based project. Perhaps a project like [typeshed](https://github.com/python/typeshed/) might be a better fit?
