### ISSUE TITLE
_greenlet.cpython-39-darwin.so: mach-o, but wrong architecture

### ISSUE THREAD

**Issue by cx4** [python-greenlet/greenlet#247]
Apple arm64 M1 chip

Python 3.9.6

`greenlet.cpython-39-darwin.so: mach-o, but wrong architecture`

**Comment by jamadden** [comment]
We don't distribute wheels for Apple silicon, so I don't know how you obtained that binary.

**Comment by cx4** [comment]
i install 'playwright' python version  , and this tool depends on the greenlet you developed

**Comment by zarinpy** [comment]
@jamadden  I have this problem too
