### ISSUE TITLE
pypy3.7 installation

### ISSUE THREAD

**Issue by lucifer-wsp** [python-greenlet/greenlet#248]
I have a problem with dependencies referencing "greenlet" in my project, and now when I switch to pypy3.7, the direct installation fails, so I have to remove the dependencies.

when i run "poetry install", occur errors :

- Updating greenlet (0.4.13 /usr/local/pypy3.7-v7.3.5-linux64/lib_pypy -> 1.1.0)

[EnvCommandError]
Command ['/usr/local/pypy/bin/python', '-m', 'pip', 'uninstall', 'greenlet', '-y'] errored with the following return code 1, and output: 
Found existing installation: greenlet 0.4.13
ERROR: Cannot uninstall 'greenlet'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Anyone have a problem with this.

**Comment by jamadden** [comment]
You need to write your dependency on greenlet using [PEP 497](https://www.python.org/dev/peps/pep-0496/) environment markers so  that it is not requested on PyPy. For example, this is [is what gevent does](https://github.com/gevent/gevent/blob/f6658dd9608e90b5ec8338613d29cc4851cbe965/setup.py#L203):

```python
    'greenlet >= 0.4.17, < 2.0; platform_python_implementation=="CPython"',
```

**Comment by lucifer-wsp** [comment]
Okay, i will try it but i use `poetry update ` to generate poetry.lock file, I'm not sure I can edit the lock file directly. Anyway thank you for your answer.

**Comment by lucifer-wsp** [comment]
It works, thank you very much.
