### ISSUE TITLE
undefined symbol: _PyTrash_thread_deposit_object on Ubuntu 12.10 amd_64

### ISSUE THREAD

**Issue by moisespsena** [python-greenlet/greenlet#25]
No milestone
No one is assigned

I am using gevent socketio package, which requires greenlet, but I am getting this error when using the package with virtualenv 1.7.1.2.

greenlet = **import**('greenlet').greenlet
ImportError: /home/moi/python-env/e2/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object

**Comment by abs07** [comment]
@snaury I am having the same problem
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2023
Could you please check and help me with this
