### ISSUE TITLE
Python > 3.8 install issues...

### ISSUE THREAD

**Issue by lwoydziak** [python-greenlet/greenlet#275]
I am trying to install greenlet on python 3.9 and get the following error:

 => ERROR [23/27] RUN pip3 install greenlet==0.4.13                                                                                                4.2s
------
 > [23/27] RUN pip3 install greenlet==0.4.13:
#26 1.671 Collecting greenlet==0.4.13
#26 1.877   Downloading greenlet-0.4.13.tar.gz (58 kB)
#26 2.317 Building wheels for collected packages: greenlet
#26 2.318   Building wheel for greenlet (setup.py): started
#26 2.910   Building wheel for greenlet (setup.py): finished with status 'error'
#26 2.912   ERROR: Command errored out with exit status 1:
#26 2.912    command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x33xsqov/greenlet_97941313463c487b8bb98f3321dd41b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x33xsqov/greenlet_97941313463c487b8bb98f3321dd41b6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9a316xwc
#26 2.912        cwd: /tmp/pip-install-x33xsqov/greenlet_97941313463c487b8bb98f3321dd41b6/
#26 2.912   Complete output (24 lines):
#26 2.912   running bdist_wheel
#26 2.912   running build
#26 2.912   running build_ext
#26 2.912   building 'greenlet' extension
#26 2.912   creating build
#26 2.912   creating build/temp.linux-x86_64-3.9
#26 2.912   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c greenlet.c -o build/temp.linux-x86_64-3.9/greenlet.o
#26 2.912   greenlet.c: In function ‘g_initialstub’:
#26 2.912   greenlet.c:810:4: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
#26 2.912     810 |    result = PyEval_CallObjectWithKeywords(
#26 2.912         |    ^~~~~~
#26 2.912   In file included from /usr/local/include/python3.9/Python.h:141,
#26 2.912                    from greenlet.h:8,
#26 2.912                    from greenlet.c:5:
#26 2.912   /usr/local/include/python3.9/ceval.h:17:43: note: declared here
#26 2.912      17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
#26 2.912         |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#26 2.912   greenlet.c: In function ‘green_dealloc’:
#26 2.912   greenlet.c:1021:4: error: ‘_Py_DEC_REFTOTAL’ undeclared (first use in this function); did you mean ‘_Py_DECREF’?
#26 2.912    1021 |    _Py_DEC_REFTOTAL;
#26 2.912         |    ^~~~~~~~~~~~~~~~
#26 2.912         |    _Py_DECREF
#26 2.912   greenlet.c:1021:4: note: each undeclared identifier is reported only once for each function it appears in
#26 2.912   error: command '/usr/bin/gcc' failed with exit code 1
#26 2.912   ----------------------------------------
#26 2.912   ERROR: Failed building wheel for greenlet
#26 2.913   Running setup.py clean for greenlet
#26 3.361 Failed to build greenlet
#26 3.505 Installing collected packages: greenlet
#26 3.510     Running setup.py install for greenlet: started
#26 4.036     Running setup.py install for greenlet: finished with status 'error'
#26 4.037     ERROR: Command errored out with exit status 1:
#26 4.037      command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x33xsqov/greenlet_97941313463c487b8bb98f3321dd41b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x33xsqov/greenlet_97941313463c487b8bb98f3321dd41b6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-969snmck/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/greenlet
#26 4.037          cwd: /tmp/pip-install-x33xsqov/greenlet_97941313463c487b8bb98f3321dd41b6/
#26 4.037     Complete output (24 lines):
#26 4.037     running install
#26 4.037     running build
#26 4.037     running build_ext
#26 4.037     building 'greenlet' extension
#26 4.037     creating build
#26 4.037     creating build/temp.linux-x86_64-3.9
#26 4.037     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c greenlet.c -o build/temp.linux-x86_64-3.9/greenlet.o
#26 4.037     greenlet.c: In function ‘g_initialstub’:
#26 4.037     greenlet.c:810:4: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
#26 4.037       810 |    result = PyEval_CallObjectWithKeywords(
#26 4.037           |    ^~~~~~
#26 4.037     In file included from /usr/local/include/python3.9/Python.h:141,
#26 4.037                      from greenlet.h:8,
#26 4.037                      from greenlet.c:5:
#26 4.037     /usr/local/include/python3.9/ceval.h:17:43: note: declared here
#26 4.037        17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
#26 4.037           |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#26 4.037     greenlet.c: In function ‘green_dealloc’:
#26 4.037     greenlet.c:1021:4: error: ‘_Py_DEC_REFTOTAL’ undeclared (first use in this function); did you mean ‘_Py_DECREF’?
#26 4.037      1021 |    _Py_DEC_REFTOTAL;
#26 4.037           |    ^~~~~~~~~~~~~~~~
#26 4.037           |    _Py_DECREF
#26 4.037     greenlet.c:1021:4: note: each undeclared identifier is reported only once for each function it appears in
#26 4.037     error: command '/usr/bin/gcc' failed with exit code 1
#26 4.037     ----------------------------------------
#26 4.040 ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x33xsqov/greenlet_97941313463c487b8bb98f3321dd41b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x33xsqov/greenlet_97941313463c487b8bb98f3321dd41b6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-969snmck/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/greenlet Check the logs for full command output.
#26 4.047 WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
#26 4.047 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip3 install greenlet==0.4.13]: exit code: 1

I am rolling back to 3.8 which works, but thought you all would like to know,
--Luke

**Comment by jamadden** [comment]
Thanks for the report. greenlet 0.4.13 does not support Python 3.8 or newer; it was last updated for Python 3.7 back in 2018. Support for Python 3.9 was added in greenlet 0.4.16. The current release of greenlet is 1.1.2 which supports up to Python 3.10.
