### ISSUE TITLE
Greenlet Build fail with docker (python:alpine)

### ISSUE THREAD

**Issue by Ezak91** [python-greenlet/greenlet#279]
#11 329.7   running build
#11 329.7   running build_py
#11 329.7   creating build
#11 329.7   creating build/lib.linux-x86_64-3.10
#11 329.7   creating build/lib.linux-x86_64-3.10/greenlet
#11 329.7   copying src/greenlet/__init__.py -> build/lib.linux-x86_64-3.10/greenlet
#11 329.7   creating build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_contextvars.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_cpp.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_version.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_stack_saved.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_generator.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_gc.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_extension_interface.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_leaks.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_weakref.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_generator_nested.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_tracing.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_throw.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/__init__.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/test_greenlet.py -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   running egg_info
#11 329.7   writing src/greenlet.egg-info/PKG-INFO
#11 329.7   writing dependency_links to src/greenlet.egg-info/dependency_links.txt
#11 329.7   writing requirements to src/greenlet.egg-info/requires.txt
#11 329.7   writing top-level names to src/greenlet.egg-info/top_level.txt
#11 329.7   reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
#11 329.7   reading manifest template 'MANIFEST.in'
#11 329.7   no previously-included directories found matching 'docs/_build'
#11 329.7   warning: no files found matching '*.py' under directory 'appveyor'
#11 329.7   warning: no previously-included files matching '*.pyc' found anywhere in distribution
#11 329.7   warning: no previously-included files matching '*.pyd' found anywhere in distribution
#11 329.7   warning: no previously-included files matching '*.so' found anywhere in distribution
#11 329.7   warning: no previously-included files matching '.coverage' found anywhere in distribution
#11 329.7   adding license file 'LICENSE'
#11 329.7   adding license file 'LICENSE.PSF'
#11 329.7   adding license file 'AUTHORS'
#11 329.7   writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
#11 329.7   copying src/greenlet/greenlet.c -> build/lib.linux-x86_64-3.10/greenlet
#11 329.7   copying src/greenlet/greenlet.h -> build/lib.linux-x86_64-3.10/greenlet
#11 329.7   copying src/greenlet/slp_platformselect.h -> build/lib.linux-x86_64-3.10/greenlet
#11 329.7   creating build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_mips_unix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_s390_unix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_x32_unix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/platform/switch_x86_unix.h -> build/lib.linux-x86_64-3.10/greenlet/platform
#11 329.7   copying src/greenlet/tests/_test_extension.c -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.linux-x86_64-3.10/greenlet/tests
#11 329.7   running build_ext
#11 329.7   building 'greenlet._greenlet' extension
#11 329.7   creating build/temp.linux-x86_64-3.10
#11 329.7   creating build/temp.linux-x86_64-3.10/src
#11 329.7   creating build/temp.linux-x86_64-3.10/src/greenlet
#11 329.7   gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.10 -c src/greenlet/greenlet.c -o build/temp.linux-x86_64-3.10/src/greenlet/greenlet.o
#11 329.7   src/greenlet/greenlet.c: In function 'g_calltrace':
#11 329.7   src/greenlet/greenlet.c:570:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'use_tracing'; did you mean 'tracing'?
#11 329.7     570 |     tstate->use_tracing = 0;
#11 329.7         |             ^~~~~~~~~~~
#11 329.7         |             tracing
#11 329.7   src/greenlet/greenlet.c:573:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'use_tracing'; did you mean 'tracing'?
#11 329.7     573 |     tstate->use_tracing =
#11 329.7         |             ^~~~~~~~~~~
#11 329.7         |             tracing
#11 329.7   error: command '/usr/bin/gcc' failed with exit code 1
#11 329.7   ----------------------------------------
#11 329.7   ERROR: Failed building wheel for greenlet

can anyone help?

**Comment by jamadden** [comment]
You appear to be trying to compile an old version of greenlet against Python 3.10, but that old version doesn't support Python 3.10. You'll need to use a version of greenlet that's compatible with 3.10; I recommend 1.1.2.
