### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by 3nprob** [python-greenlet/greenlet#298]

**Comment by 3nprob** [comment]
@jamadden what's up? Seems to be multiple issues that need resolving. Or, if they're not intended to tell the state of the codebase, maybe remove the 
![image](https://user-images.githubusercontent.com/74199244/162132480-caa12e6f-d629-4cf2-b84f-90fee03bd32b.png)
 banner from pypi?

**Comment by jamadden** [comment]
If you actually look, you'll see that the tests are green. PyPI captures and caches copies of all images used on a project's page at some point during project upload, and one particular time it did that, the master branch happened to have just failed. PyPI releases are immutable so there's nothing that can be done.

A three-word title on an issue with no body looks an awful lot like drive-by spam. Providing details makes it much less likely to be ignored.
