### ISSUE TITLE
Documentation Request: What are the changes in version 1.1.3?

### ISSUE THREAD

**Issue by billdenney** [python-greenlet/greenlet#314]
Version 1.1.3 is released, but it is not mentioned in the change log (https://github.com/python-greenlet/greenlet/blob/fa91f03d5ec8d46017300cb6b161ec3dbe0d3a0c/CHANGES.rst).  Can information on the changes in version 1.1.3 please be added to the changelog?

**Comment by jamadden** [comment]
They are: https://greenlet.readthedocs.io/en/stable/changes.html#id1
![Untitled](https://user-images.githubusercontent.com/1256082/194054247-aa97c7f6-44b4-405b-94f3-e9785d5fa6d1.png)

**Comment by billdenney** [comment]
Thanks!
