### ISSUE TITLE
PyPi missing 3.11 Windows Wheels

### ISSUE THREAD

**Issue by CreatingNull** [python-greenlet/greenlet#317]
With Python 3.11 being officially released, is it possible to generate a 3.11 windows wheel on PyPi?

I can see in 1.1.3 (https://github.com/python-greenlet/greenlet/commit/69ee8fa79e0bb754a76c344f073c259723c834fc) that windows wheels were intentionally excluded, assuming this is due to appveyor [not having support for 3.11](https://github.com/appveyor/ci/issues/3844) yet?
Building the wheels locally works on windows, but this may not be possible for many users environments.

I figured I'd ask the question, as lot of packages rely on this awesome lib and some other users are bound to be wondering the same thing.

Thanks!

**Comment by jamadden** [comment]
Correct, Windows wheels will be dependent on the CI provider having Python 3.11 available.

**Comment by arcivanov** [comment]
FYI, Windows GH Actions do have 3.11rc available, we use it at PyB: 
https://github.com/pybuilder/pybuilder/actions/runs/3214484494/jobs/5254981485

**Comment by algot** [comment]
Why this issue is closed?
I have an issue with building the wheel on Windows 10 while I'm using python 3.11

**Comment by yogevyuval** [comment]
@jamadden Missing wheels on linux as well, could we maybe track this in an issue?
