### ISSUE TITLE
creating new greenlets appears to leak memory rapidly in python 3.11 / linux

### ISSUE THREAD

**Issue by zzzeek** [python-greenlet/greenlet#328]
hi there -

This is indirect from SQLAlchemy where we use greenlet for our asyncio implementation, reported in https://github.com/sqlalchemy/sqlalchemy/issues/8763.

The below script creates a greenlet and calls one switch.   Running on linux under any Python 3.11 version with greenlet installed from pypi (`greenlet-2.0.0.post0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`), the script below grows by about 10M per second.  Under Python 3.10, memory is flat at about 10 megs resident.

```py
import greenlet
import time


def greenlet_spawn(fn, *args, **kwargs):
    context = greenlet.greenlet(fn, greenlet.getcurrent())
    result = context.switch(*args, **kwargs)
    return result



def hi():
    time.sleep(.001)
    return "hello"

def go():
    while True:
        print(greenlet_spawn(hi))
go()

```

**Comment by salty-horse** [comment]
Previously reported here: https://github.com/gevent/gevent/issues/1924

**Comment by zzzeek** [comment]
thanks!!!

**Comment by zzzeek** [comment]
The test program above works now however in our integration case we are still seeing rapid memory increases, unfortunately.  I will attempt to devise a new test case.

**Comment by zzzeek** [comment]
hMmmmmm OK I think you are good actually, there now seems to be an entirely different memory leak, again python 3.11 only , either in the sqlite3 module or the aiosqlite module.   how strange huh?   I'll keep you posted but in our *original* original case with asyncpg (which is the important driver), memory seems to be stable.

**Comment by zzzeek** [comment]
OK we're good here, aiosqlite has some problem, strange, but i can reproduce without greenlet involved. thanks for the quick fix!

**Comment by zzzeek** [comment]
@jamadden  I'm still in the disbelief stage, but it appears python 3.11 itself has a similar problem as the one here, **with threading.Thread()**.  That is, the program below which is the threading equivalent also leaks memory at a similar rate:

```py
from threading import Thread

while True:
    t1 = Thread()
    t1.start()

```

I'm going to quadruple check this before reporting to them but do you think the issue you found here might be similarly involved for Python's own Thread object?

**Comment by zzzeek** [comment]
OK!  I hope they find this useful when they come in to look at this issue (also surprised noone has triaged it yet, they are usually pretty quick)

**Comment by pratik0907** [comment]
I'm using greenlet version 3.0.3 and still facing this issue

**Comment by salty-horse** [comment]
> I'm using greenlet version 3.0.3 and still facing this issue

Have you tested with the script at the top? It runs fine for me (no memory leaks) with greenlet 3.0.3 on Python 3.12.3.

**Comment by pratik0907** [comment]
Yes, 
Python version: 3.11.6
Greenlet version: 3.0.3

**Comment by salty-horse** [comment]
Python 3.11.6 is also working fine for me.

**Comment by pratik0907** [comment]
Not working for me, memory utilization keeps on increasing on every request. (Replicated in local env)

**Comment by pratik0907** [comment]
python = "^3.11"
uvicorn = {extras = ["standard"], version = "^0.25.0"}
fastapi = "^0.108.0"
pydantic = "^2.5.3"
celery = "^5.3.6"
aiohttp = "^3.9.1"
python-dotenv = "^1.0.0"
asyncpg = "^0.29.0"
python-json-logger = "^2.0.7"
tenacity = "^8.2.3"
sqlalchemy = "^2.0.24"
alembic = "^1.13.1"
ldclient-py = "^6.9.1"
sentry-sdk = "^1.39.1"
newrelic = "^9.3.0"
greenlet = "^3.0.3"

**Comment by greatitman** [comment]
I also have the same problem as [pratik0907](https://github.com/pratik0907) 。 I haved tried python3.10 3.11，the mem leak still exists。 How about you now @pratik0907
