### ISSUE TITLE
greenlet v2.0.1 doesnot work with gevent 20.9.0

### ISSUE THREAD

**Issue by hpatelbitglass** [python-greenlet/greenlet#331]
Last compatible version for greenlet is 1.1.3.post0.

Error: ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject

**Comment by jamadden** [comment]
Yes. This is well documented. Only gevent 22.10.2 and later use greenlet 2; older versions require <= greenlet 1.  Unfortunately, very old versions of gevent such as the one you mention do not have an upper bound version pin for greenlet, so installers will not enforce this.
