### ISSUE TITLE
error: specialization of 'template<class IsPy37> const OwnedObject greenlet::Greenlet::context(typename IsPy37::IsIt) const' in different namespace

### ISSUE THREAD

**Issue by jameshilliard** [python-greenlet/greenlet#334]
I'm seeing [this error in our autobuilders](http://autobuild.buildroot.net/results/eb6/eb67fe65c6ff245204c5c163b6704b1e5aa29a6a/build-end.log) for greenlet 2.0.1.
```cpp
creating build/temp.linux-x86_64-3.11/src/greenlet
/usr/bin/gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -I/home/buildroot/autobuild/instance-0/output-1/host/include -O2 -I/home/buildroot/autobuild/instance-0/output-1/host/include -I/home/buildroot/autobuild/instance-0/output-1/host/include -fPIC -I/home/buildroot/autobuild/instance-0/output-1/host/include/python3.11 -c src/greenlet/greenlet.cpp -o build/temp.linux-x86_64-3.11/src/greenlet/greenlet.o
src/greenlet/greenlet.cpp:2511:64: error: specialization of 'template<class IsPy37> const OwnedObject greenlet::Greenlet::context(typename IsPy37::IsIt) const' in different namespace [-fpermissive]
 Greenlet::context<GREENLET_WHEN_PY37>(GREENLET_WHEN_PY37::Yes) const
                                                                ^~~~~
In file included from src/greenlet/greenlet_internal.hpp:20:0,
                 from src/greenlet/greenlet.cpp:19:
src/greenlet/greenlet_greenlet.hpp:333:27: error:   from definition of 'template<class IsPy37> const OwnedObject greenlet::Greenlet::context(typename IsPy37::IsIt) const' [-fpermissive]
         const OwnedObject context(const typename IsPy37::IsIt=nullptr) const;
                           ^~~~~~~
src/greenlet/greenlet.cpp:2540:71: error: specialization of 'template<class IsPy37> const OwnedObject greenlet::Greenlet::context(typename IsPy37::IsIt) const' in different namespace [-fpermissive]
 Greenlet::context<GREENLET_WHEN_NOT_PY37>(GREENLET_WHEN_NOT_PY37::No) const
                                                                       ^~~~~
In file included from src/greenlet/greenlet_internal.hpp:20:0,
                 from src/greenlet/greenlet.cpp:19:
src/greenlet/greenlet_greenlet.hpp:333:27: error:   from definition of 'template<class IsPy37> const OwnedObject greenlet::Greenlet::context(typename IsPy37::IsIt) const' [-fpermissive]
         const OwnedObject context(const typename IsPy37::IsIt=nullptr) const;
                           ^~~~~~~
src/greenlet/greenlet.cpp:2562:89: error: specialization of 'template<class IsPy37> void greenlet::Greenlet::context(greenlet::refs::BorrowedObject, typename IsPy37::IsIt)' in different namespace [-fpermissive]
 void Greenlet::context<GREENLET_WHEN_PY37>(BorrowedObject given, GREENLET_WHEN_PY37::Yes)
                                                                                         ^
In file included from src/greenlet/greenlet_internal.hpp:20:0,
                 from src/greenlet/greenlet.cpp:19:
src/greenlet/greenlet_greenlet.hpp:336:21: error:   from definition of 'template<class IsPy37> void greenlet::Greenlet::context(greenlet::refs::BorrowedObject, typename IsPy37::IsIt)' [-fpermissive]
         inline void context(refs::BorrowedObject new_context, typename IsPy37::IsIt=nullptr);
                     ^~~~~~~
src/greenlet/greenlet.cpp:2597:99: error: specialization of 'template<class IsPy37> void greenlet::Greenlet::context(greenlet::refs::BorrowedObject, typename IsPy37::IsIt)' in different namespace [-fpermissive]
 Greenlet::context<GREENLET_WHEN_NOT_PY37>(BorrowedObject UNUSED(given), GREENLET_WHEN_NOT_PY37::No)
                                                                                                   ^
In file included from src/greenlet/greenlet_internal.hpp:20:0,
                 from src/greenlet/greenlet.cpp:19:
src/greenlet/greenlet_greenlet.hpp:336:21: error:   from definition of 'template<class IsPy37> void greenlet::Greenlet::context(greenlet::refs::BorrowedObject, typename IsPy37::IsIt)' [-fpermissive]
         inline void context(refs::BorrowedObject new_context, typename IsPy37::IsIt=nullptr);
                     ^~~~~~~
error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by dwt** [comment]
Same while building this for an ARM docker container (I'm on apple silicon)

**Comment by dwt** [comment]
Anyway, I don't like that I have to set the build flag for _all_ packages and AFAIK there is no way to set it only for the greenlet package. Is there a workaround? I just had a very similar bug on [rpy2](https://github.com/rpy2/rpy2/pull/964/files) where this was an easy fix. Is there anything that the community can do to help this along?

**Comment by jamadden** [comment]
I don't recall seeing errors like that with any recent gcc versions (clang is a different story and it was necessary to specifically opt-in to newer standards there, although I don't recall exactly why).

It would probably help to know exactly what platforms and exactly what compiler versions are presenting this error; presumably it's not a platform that is tested and produces binary wheels on our CI system. If that can be narrowed down sufficiently, perhaps code could be added to setup.py to add necessary additional compiler flags as is done for, e.g, clang and msvc.

If you need to set an environment variable to pass flags to the compiler, it shouldn't be necessary to set that environment variable globally, only when building greenlet. This may mean you need a two-step installation process, such as `(CPPFLAGS=--std=gnu++11 pip install -c constraints.txt greenlet) && pip install -c constraints -r requirements`

**Comment by MIHIRZZ** [comment]
Hi there, I was getting the same error. Specifically in Python. My error got resolved by using following flask packages:

- flask=1.0.2
- flask-sqlalchemy=2.3.2
- flask-cors=3.0.6
- jinja2=2.10

the versions are compatible with my application. You can use yours compatible version. I hope it will resolve this error as mine.

**Comment by jameshilliard** [comment]
> It would probably help to know exactly what platforms and exactly what compiler versions are presenting this error; presumably it's not a platform that is tested and produces binary wheels on our CI system. If that can be narrowed down sufficiently, perhaps code could be added to setup.py to add necessary additional compiler flags as is done for, e.g, clang and msvc.

You can get an idea of the build configurations hitting this failure by looking at our autobuilder failures for the package [here](http://autobuild.buildroot.net/?reason=python-greenlet-2.0.1).

**Comment by jamadden** [comment]
> You can get an idea of the build configurations hitting this failure by looking at our autobuilder failures 

Perhaps you can, but other than seeing a list of platforms, that doesn't answer the important questions about the compiler. I mean, maybe it's somewhere in that 4500 line `config` file, but I'm not going to try to guess. Or maybe I just missed it; it certainly didn't seem obvious.

I *can* try to make an educated guess as to what a fix might look like...
