### ISSUE TITLE
copy or deepcopy of a greenlet object

### ISSUE THREAD

**Issue by blankjul** [python-greenlet/greenlet#353]
One of the major downsides of generators is that the functions can neither be serialized nor copied.
When I came across `greenlet`, I was hoping to be able to use this instead of generators but keep my object serializable (instead of having all users switch to Stackless Python which is not a true alternative in my opinion). This would be amazing and help many developers to use the best of both worlds (generators and serialization).

I was trying the following: 

```
class MyGreenlet(greenlet):
    pass

g = MyGreenlet()
gp = deepcopy(g)
```

which throws 

```
Traceback (most recent call last):
  File "/Users/blankjul/workspace/pymoo-dev/pymoo/algorithms/soo/nonconvex/random_search.py", line 32, in <module>
    gp = deepcopy(g)
  File "/Users/blankjul/opt/anaconda3/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot serialize 'MyGreenlet' object
```

Is there any way or hack to be able to deep copy a greenlet? What is the reason it is forbidden or not possible?

PS: In the example above the greenlet is not even running. However, I assume a running greenlet is probably the bigger challenge.

**Comment by jamadden** [comment]
Greenlets cannot be copied for the same reason a thread cannot be copied: they both contain native stacks that rely on their position in memory.  Making a copy would move that memory, and invalidate anything that referenced it --- such as  function return addresses.
