### ISSUE TITLE
RDE: please restore doc/conf.py (sphinx support)

### ISSUE THREAD

**Issue by kloczek** [python-greenlet/greenlet#354]
Up to now was possible to generate documentation using spjix and have handy man page with `greenlet` documentation.
Looks like that support gone 😞

**Comment by kloczek** [comment]
BTW:  sphinx an use as well .md files as input resources.

**Comment by jamadden** [comment]
Documentation is still built with Sphinx from the [`docs` directory](https://github.com/python-greenlet/greenlet/tree/master/docs).
