### ISSUE TITLE
Using Greenlet to Make PyMongo Async

### ISSUE THREAD

**Issue by blink1073** [python-greenlet/greenlet#359]
Hi all, I am a maintainer of [`pymongo`](https://github.com/mongodb/mongo-python-driver), the Python driver for MongoDB.  

We are looking to use `greentlet` to merge the async version of our driver, [`motor`](https://github.com/mongodb/motor), into the `pymongo` code base.

If you're interested in the details, I wrote up a short proposal in a [gist](https://gist.github.com/blink1073/3873afd23977a8ab94a423127f2ca2ce).  

For context on why I opened #358, we provide `s390x`wheels in PyMongo and wished to add the same here.

I'm opening this issue to:

- Thank you for `greenlet`!
- Ask if you have any input/suggestions on this idea
- Help with the maintenance of `greenlet` if we take it on as a dependency

**Comment by jamadden** [comment]
Fixed in #358
