### ISSUE TITLE
pytest is not compatible with greenlet

### ISSUE THREAD

**Issue by salabim** [python-greenlet/greenlet#362]
I am trying to run some pytest tests with code that uses greenlets. But, that doesn't seem to work.
I have seen that there are patches for the gevent module, but I can't find anything for greenlet.
Is there a patch for greenlet, and if not, it would be super helpful to have it.

**Comment by jamadden** [comment]
I have no idea. This doesn't seem like a question for greenlet, it seems like a question for pytest.

Personally,  I have no issues running tests with greenlet or gevent using `unittest` or `zope.testrunner`, and they don't have to do anything special, so I don't see why any other testrunner would need to. But pytest...
