### ISSUE TITLE
Pre-release wheels for macOS have invalid ABI tag

### ISSUE THREAD

**Issue by layday** [python-greenlet/greenlet#369]
The macOS wheels for version [3.0.0rc3](https://pypi.org/project/greenlet/3.0.0rc3/#files) uploaded to PyPI have an invalid ABI tag (`universal2`), which pip refuses to process. `greenlet-3.0.0rc3-cp312-universal2-macosx_10_9_universal2.whl` should be `greenlet-3.0.0rc3-cp312-cp312-macosx_10_9_universal2.whl`, and so on.

**Comment by edgarrmondragon** [comment]
I think the wheels for [3.0.0](https://pypi.org/project/greenlet/3.0.0/#files) have a similar problem:

```diff
- greenlet-3.0.0-cp312-universal2-macosx_10_9_universal2.whl
+ greenlet-3.0.0-cp312-cp312-macosx_10_9_universal2.whl
```

**Comment by layday** [comment]
Yes, these wheels are not installable.

**Comment by tasansal** [comment]
Just noticed this in our CI/CD on Azure DevOps.

It installs on Arm64 M1 Max, but on x86 Mac CI/CD, it fails because it can't find the candidate.

This is on production 3.0.0

**Comment by edgarrmondragon** [comment]
I started a PR: https://github.com/python-greenlet/greenlet/pull/372

**Comment by edgarrmondragon** [comment]
I think the wheel tags were fixed by https://github.com/python-greenlet/greenlet/commit/4418940827246bfadccc256ecd3c1107a5c535a8 to can probably be closed

**Comment by jamadden** [comment]
Everything looks correct to me in 3.0.2.

**Comment by layday** [comment]
The [macOS 11.0 tag](https://github.com/python-greenlet/greenlet/blob/edbdda27ab1983ac157b588dd0c04816cb31b0ea/.github/workflows/tests.yml#L67) that is currently in use means that macOS wheels are no longer installable using pip depending on the version of the macOS SDK Python was built against, because the version of packaging that pip bundles is two years out of date and does not emit new-style macOS version tags (see https://github.com/pypa/packaging/issues/497).  Upgrading packaging in pip is blocked on legacy version specifier removal (https://github.com/pypa/pip/issues/11715).  Please use `macosx_10_16_universal2` instead of `macosx_11_0_universal2` if the earliest macOS version you support is indeed Big Sur.

**Comment by jamadden** [comment]
The earliest tested macOS is macOS 12 (Monterey).
