### ISSUE TITLE
sdist missing for 3.0.0

### ISSUE THREAD

**Issue by mgorny** [python-greenlet/greenlet#371]
There is no source distribution on https://pypi.org/project/greenlet/3.0.0/#files. We're using these to build greenlet for Gentoo; not to mention it makes it impossible to build greenlet on any platform that's not covered by wheels.

**Comment by Scrumplex** [comment]
We have the same issue over at https://github.com/NixOS/nixpkgs/. We can switch to fetching the source archive from GitHub for now, but usually we do PyPI.

**Comment by Scrumplex** [comment]
Looks like we have a source archive on PyPI now!

![PyPI source archive](https://scrumplex.rocks/img/1696722005_uuVa4g.png)

**Comment by mgorny** [comment]
Yes, thank you.
