### ISSUE TITLE
Greenlet is not building.

### ISSUE THREAD

**Issue by kelvindoe22** [python-greenlet/greenlet#399]
Please fix, greenlet is not building. I don't know why

**Comment by kelvindoe22** [comment]
reenlet/TGreenlet.cpp: In member function 'virtual greenlet::Greenlet::switchstack_result_t greenlet::Greenlet::g_switchstack()':
      src/greenlet/TGreenlet.cpp:157: error: 'class greenlet::Greenlet' has no member named 'thread_state'
      src/greenlet/TGreenlet.cpp:157: error: 'class greenlet::Greenlet' has no member named 'self'
      src/greenlet/TGreenlet.cpp:162: error: 'class greenlet::Greenlet' has no member named 'thread_state'
      src/greenlet/TGreenlet.cpp:164: error: 'class greenlet::Greenlet' has no member named 'thread_state'
      src/greenlet/TGreenlet.cpp:167: error: base operand of '->' has non-pointer type 'greenlet::refs::BorrowedGreenlet'
      src/greenlet/TGreenlet.cpp:168: error: base operand of '->' has non-pointer type 'greenlet::refs::BorrowedGreenlet'
      src/greenlet/TGreenlet.cpp:169: error: 'class greenlet::PythonState' has no member named 'will_switch_from'
      src/greenlet/TGreenlet.cpp:177: error: 'class greenlet::Greenlet' has no member named 'force_slp_switch_error'
      src/greenlet/TGreenlet.cpp:202: error: 'nullptr' was not declared in this scope
      src/greenlet/TGreenlet.cpp:209: error: 'class greenlet::Greenlet' has no member named 'g_switchstack_success'
      src/greenlet/TGreenlet.cpp: In member function 'void greenlet::Greenlet::check_switch_allowed() const':
      src/greenlet/TGreenlet.cpp:237: error: conversion from 'const greenlet::refs::BorrowedMainGreenlet' to 'bool' is ambiguous
      src/greenlet/greenlet_refs.hpp:562: note: candidates are: greenlet::refs::_BorrowedGreenlet<T, TC>::operator PyObject*() const [with T = _greenlet, void (* TC)(void*) = greenlet::refs::MainGreenletExactChecker]
      src/greenlet/greenlet_refs.hpp:531: note:                 greenlet::refs::BorrowedReference<T, <anonymous> >::operator T*() const [with T= _greenlet, void (* TC)(void*) = greenlet::refs::MainGreenletExactChecker]
      src/greenlet/TGreenlet.cpp:242: error: base operand of '->' has non-pointer type 'const greenlet::refs::BorrowedMainGreenlet'
      src/greenlet/TGreenlet.cpp:256: error: 'g_thread_state_global' was not declared in this scope
      src/greenlet/TGreenlet.cpp:259: error: ambiguous overload for 'operator!=' in 'current_main_greenlet != main_greenlet'
      src/greenlet/TGreenlet.cpp:259: note: candidates are: operator!=(_greenlet*, _greenlet*) <built-in>
      src/greenlet/TGreenlet.cpp:259: note:                 operator!=(PyObject*, PyObject*) <built-in>
      src/greenlet/TGreenlet.cpp:259: note:                 operator!=(_greenlet*, _greenlet*) <built-in>
      src/greenlet/TGreenlet.cpp:259: note:                 operator!=(_greenlet*, _greenlet*) <built-in>
      src/greenlet/TGreenlet.cpp:259: note:                 operator!=(PyObject*, PyObject*) <built-in>
      src/greenlet/TGreenlet.cpp:259: note:                 operator!=(PyObject*, PyObject*) <built-in>
      src/greenlet/TGreenlet.cpp:265: error: ambiguous overload for 'operator!=' in 'current_main_greenlet != main_greenlet'
      src/greenlet/TGreenlet.cpp:265: note: candidates are: operator!=(_greenlet*, _greenlet*) <built-in>
      src/greenlet/TGreenlet.cpp:265: note:                 operator!=(PyObject*, PyObject*) <built-in>
      src/greenlet/TGreenlet.cpp:265: note:                 operator!=(_greenlet*, _greenlet*) <built-in>
      src/greenlet/TGreenlet.cpp:265: note:                 operator!=(_greenlet*, _greenlet*) <built-in>
      src/greenlet/TGreenlet.cpp:265: note:                 operator!=(PyObject*, PyObject*) <built-in>
      src/greenlet/TGreenlet.cpp:265: note:                 operator!=(PyObject*, PyObject*) <built-in>
      src/greenlet/TGreenlet.cpp:269: error: base operand of '->' has non-pointer type 'const greenlet::refs::BorrowedMainGreenlet'
      src/greenlet/TGreenlet.cpp: In member function 'const greenlet::refs::OwnedObject greenlet::Greenlet::context() const':
      src/greenlet/TGreenlet.cpp:286: error: 'g_thread_state_global' was not declared in this scope
      src/greenlet/TGreenlet.cpp:286: error: 'const class greenlet::Greenlet' has no member named 'self'
      src/greenlet/TGreenlet.cpp:299: error: no match for 'operator!' in '!result'
      src/greenlet/TGreenlet.cpp:299: note: candidates are: operator!(bool) <built-in>
      src/greenlet/TGreenlet.cpp: In member function 'void greenlet::Greenlet::context(greenlet::refs::BorrowedObject)':
      src/greenlet/TGreenlet.cpp:313: error: 'struct greenlet::refs::BorrowedObject' has no member named 'is_None'
      src/greenlet/TGreenlet.cpp:315: error: 'nullptr' was not declared in this scope
      src/greenlet/TGreenlet.cpp:323: error: 'g_thread_state_global' was not declared in this scope
      src/greenlet/TGreenlet.cpp:323: error: 'class greenlet::Greenlet' has no member named 'self'
      src/greenlet/TGreenlet.cpp: At global scope:
      src/greenlet/TGreenlet.cpp:355: error: expected initializer before 'noexcept'
      src/greenlet/greenlet.cpp:98: error: expected '}' before end of line
      src/greenlet/greenlet.cpp:98: error: expected declaration before end of line
      In file included from src/greenlet/greenlet_greenlet.hpp:11,
                       from src/greenlet/greenlet_internal.hpp:20,
                       from src/greenlet/greenlet.cpp:19:
      src/greenlet/greenlet_refs.hpp: In member function 'greenlet::refs::OwnedReference<T, <anonymous> >& greenlet::refs::OwnedReference<T, <anonymous> >::operator=(greenlet::refs::BorrowedReference<T, TC>) [with T = _object, void (* TC)(void*) = greenlet::refs::NoOpChecker]':
      src/greenlet/greenlet_thread_state.hpp:310:   instantiated from here
      src/greenlet/greenlet_refs.hpp:350: error: 'const struct greenlet::refs::BorrowedReference<_object, greenlet::refs::NoOpChecker>' has no member named 'borrow'
      src/greenlet/greenlet_refs.hpp: In member function 'greenlet::refs::OwnedReference<T, <anonymous> >& greenlet::refs::OwnedReference<T, <anonymous> >::operator=(const greenlet::refs::OwnedReference<X, XC>&) [with X = _object, void (* XC)(void*) = greenlet::refs::ContextExactChecker, T = _object, void (* TC)(void*) = greenlet::refs::NoOpChecker]':
      src/greenlet/TGreenlet.cpp:297:   instantiated from here
      src/greenlet/greenlet_refs.hpp:368: error: 'const struct greenlet::refs::OwnedReference<_object, greenlet::refs::ContextExactChecker>' has no member named 'borrow'
      src/greenlet/greenlet_greenlet.hpp: At global scope:
      src/greenlet/greenlet_greenlet.hpp:384: warning: inline function 'bool greenlet::Greenlet::is_currently_running_in_some_thread() const' used but never defined
      cc1plus: warning: unrecognized command line option "-Wno-unused-result"
      cc1plus: warning: unrecognized command line option "-Wno-unused-result"
      cc1plus: warning: unrecognized command line option "-Wno-unused-result"

**Comment by jamadden** [comment]
You didn't say anything about what you're actually doing, what platform you're on, what compiler you're using, or, you know, actually making this a useful bug report. 

So I'll guess. From "error: expected initializer before 'noexcept'",  you are probably using an old and/or unsupported compiler. 

It works fine here and in CI. In other words, this is not a greenlet problem.

**Comment by kelvindoe22** [comment]
Well a library needed greenlet so it collected it and was trying to install
it but it couldn’t and I was get c++ errors about semi colons missing and
whatnot. So I installed an older version and it worked fine. But I was on
Linux. I don’t know the exact distribution but I was on Linux and before
you close an issue make sure the issuer’s problem is solved. DH
