### ISSUE TITLE
Greenlet fails to build

### ISSUE THREAD

**Issue by kelvindoe22** [python-greenlet/greenlet#400]
MacOS sonoma
1.1.3.post0

  error: subprocess-exited-with-error
  
  × Building wheel for greenlet (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [147 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14-arm64-cpython-312
      creating build/lib.macosx-14-arm64-cpython-312/greenlet
      copying src/greenlet/__init__.py -> build/lib.macosx-14-arm64-cpython-312/greenlet
      creating build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/__init__.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      creating build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_version.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_weakref.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_gc.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_generator.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_throw.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_tracing.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_cpp.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_contextvars.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_greenlet.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_extension_interface.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/__init__.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_generator_nested.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_stack_saved.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_leaks.py -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      running egg_info
      writing src/greenlet.egg-info/PKG-INFO
      writing dependency_links to src/greenlet.egg-info/dependency_links.txt
      writing requirements to src/greenlet.egg-info/requires.txt
      writing top-level names to src/greenlet.egg-info/top_level.txt
      reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'docs/_build'
      warning: no files found matching '*.py' under directory 'appveyor'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '.coverage' found anywhere in distribution
      adding license file 'LICENSE'
      adding license file 'LICENSE.PSF'
      adding license file 'AUTHORS'
      writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
      copying src/greenlet/greenlet.c -> build/lib.macosx-14-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet.h -> build/lib.macosx-14-arm64-cpython-312/greenlet
      copying src/greenlet/slp_platformselect.h -> build/lib.macosx-14-arm64-cpython-312/greenlet
      copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_mips_unix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_s390_unix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x32_unix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x86_unix.h -> build/lib.macosx-14-arm64-cpython-312/greenlet/platform
      copying src/greenlet/tests/_test_extension.c -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-14-arm64-cpython-312/greenlet/tests
      running build_ext
      building 'greenlet._greenlet' extension
      creating build/temp.macosx-14-arm64-cpython-312
      creating build/temp.macosx-14-arm64-cpython-312/src
      creating build/temp.macosx-14-arm64-cpython-312/src/greenlet
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk "-I/Users/mac/Documents/current/site - Copy/.env/include" -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/greenlet/greenlet.c -o build/temp.macosx-14-arm64-cpython-312/src/greenlet/greenlet.o
      In file included from src/greenlet/greenlet.c:372:
      In file included from src/greenlet/slp_platformselect.h:49:
      src/greenlet/platform/switch_aarch64_gcc.h:62:51: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                                        ^
      src/greenlet/platform/switch_aarch64_gcc.h:62:35: note: use constraint modifier "w"
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                        ^~
                                        %w0
      src/greenlet/greenlet.c:531:45: error: no member named 'recursion_limit' in 'struct _ts'; did you mean 'py_recursion_limit'?
              current->recursion_depth = (tstate->recursion_limit
                                                  ^~~~~~~~~~~~~~~
                                                  py_recursion_limit
      /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/pystate.h:148:9: note: 'py_recursion_limit' declared here
          int py_recursion_limit;
              ^
      src/greenlet/greenlet.c:532:47: error: no member named 'recursion_remaining' in 'struct _ts'; did you mean 'c_recursion_remaining'?
                                          - tstate->recursion_remaining);
                                                    ^~~~~~~~~~~~~~~~~~~
                                                    c_recursion_remaining
      /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/pystate.h:150:9: note: 'c_recursion_remaining' declared here
          int c_recursion_remaining;
              ^
      src/greenlet/greenlet.c:560:57: error: no member named 'use_tracing' in 'struct _PyCFrame'
              ts__g_switchstack_use_tracing = tstate->cframe->use_tracing;
                                              ~~~~~~~~~~~~~~  ^
      src/greenlet/greenlet.c:621:25: error: no member named 'use_tracing' in 'struct _PyCFrame'
              tstate->cframe->use_tracing = ts__g_switchstack_use_tracing;
              ~~~~~~~~~~~~~~  ^
      src/greenlet/greenlet.c:624:48: error: no member named 'recursion_limit' in 'struct _ts'; did you mean 'py_recursion_limit'?
              tstate->recursion_remaining = (tstate->recursion_limit
                                                     ^~~~~~~~~~~~~~~
                                                     py_recursion_limit
      /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/pystate.h:148:9: note: 'py_recursion_limit' declared here
          int py_recursion_limit;
              ^
      src/greenlet/greenlet.c:624:17: error: no member named 'recursion_remaining' in 'struct _ts'; did you mean 'c_recursion_remaining'?
              tstate->recursion_remaining = (tstate->recursion_limit
                      ^~~~~~~~~~~~~~~~~~~
                      c_recursion_remaining
      /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/pystate.h:150:9: note: 'c_recursion_remaining' declared here
          int c_recursion_remaining;
              ^
      src/greenlet/greenlet.c:654:5: error: no member named 'use_tracing' in 'struct _PyCFrame'
          TSTATE_USE_TRACING(tstate) = 0;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      src/greenlet/greenlet.c:105:53: note: expanded from macro 'TSTATE_USE_TRACING'
      #define TSTATE_USE_TRACING(tstate) (tstate->cframe->use_tracing)
                                          ~~~~~~~~~~~~~~  ^
      src/greenlet/greenlet.c:657:5: error: no member named 'use_tracing' in 'struct _PyCFrame'
          TSTATE_USE_TRACING(tstate) =
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      src/greenlet/greenlet.c:105:53: note: expanded from macro 'TSTATE_USE_TRACING'
      #define TSTATE_USE_TRACING(tstate) (tstate->cframe->use_tracing)
                                          ~~~~~~~~~~~~~~  ^
      src/greenlet/greenlet.c:903:51: error: no member named 'recursion_limit' in 'struct _ts'; did you mean 'py_recursion_limit'?
          self->recursion_depth = (PyThreadState_GET()->recursion_limit
                                                        ^~~~~~~~~~~~~~~
                                                        py_recursion_limit
      /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/pystate.h:148:9: note: 'py_recursion_limit' declared here
          int py_recursion_limit;
              ^
      src/greenlet/greenlet.c:904:53: error: no member named 'recursion_remaining' in 'struct _ts'; did you mean 'c_recursion_remaining'?
                                   - PyThreadState_GET()->recursion_remaining);
                                                          ^~~~~~~~~~~~~~~~~~~
                                                          c_recursion_remaining
      /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/pystate.h:150:9: note: 'c_recursion_remaining' declared here

**Comment by jamadden** [comment]
You are using a very old version of greenlet. Python 3.12 is only supported in greenlet 3.0 and later.

**Comment by kelvindoe22** [comment]
Thanks I figured it out
