### ISSUE TITLE
Possibility of Forking/Duplicating a greenlet thread

### ISSUE THREAD

**Issue by tastelessjolt** [python-greenlet/greenlet#408]
Hello there, 

Is it possible to make a fork/duplicate of the paused greenlet thread at a certain point and have two copies of the thread with all the same state/stack but independent threads of execution?

Thanks in advance!

**Comment by jamadden** [comment]
The simple answer is no, that's not possible now. This is because of how the machine stack is handled. I believe  it would take a major redesign to make that work, and it would be slow.
