### ISSUE TITLE
OSX 10.10 Yosemite Error -- GCC 4.2 Failed With Exit Status 1 When Compiling bpython (uses greenlet)

### ISSUE THREAD

**Issue by weems** [python-greenlet/greenlet#76]
Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/var/folders/bc/cmnr0l6n1vb76p28m_4vlwh00000gn/T/pip-build-9yEUoD/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/bc/cmnr0l6n1vb76p28m_4vlwh00000gn/T/pip-i2DjPf-record/install-record.txt --single-version-externally-managed --compile:
    running install

    running build

    running build_ext

    building 'greenlet' extension

    creating build

    creating build/temp.macosx-10.10-x86_64-2.7

    /usr/local/bin/gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c greenlet.c -o build/temp.macosx-10.10-x86_64-2.7/greenlet.o

    <built-in>:0: error: Unknown value ‘10.10’ of -mmacosx-version-min

    error: command '/usr/local/bin/gcc-4.2' failed with exit status 1

**Comment by snaury** [comment]
Greenlet does not have `macosx-version-min` anywhere in its sources, there may be a problem with your Python or gcc installations.
