### ISSUE TITLE
del coroutine effect

### ISSUE THREAD

**Issue by jiamo** [python-greenlet/greenlet#79]
from greenlet import greenlet

	def main():
	    entry_fun_cortion.switch(0)
	    entry_fun_cortion.switch(1)
	    entry_fun_cortion.switch(2)
	    entry_fun_cortion.switch(3)
	    entry_fun_cortion.switch(4)
	    entry_fun_cortion.switch(5)

	count = 0
	def entry_fun(test):
	    global main_cortione, count,entry_fun_cortion
	    while True:
	        count += 1
	        print ("before switch id %d"%id(entry_fun_cortion))
	        aid = main_cortione.switch()
	        if count == 2:
	            del entry_fun_cortion
	            print "after del"   # continue to excute , and get id 2
	            entry_fun_cortion = greenlet(entry_fun)

	        print ("id ", id(entry_fun_cortion))
	        print "after get id ", aid

	entry_fun_cortion = greenlet(entry_fun)
	main_cortione = greenlet(main)
	main_cortione.switch()

The output is 

before switch id 140539650621840
	('id ', 140539650621840)
	after get id  1
	before switch id 140539650621840
	after del
	('id ', 140539650623120)
	after get id  2
	before switch id 140539650623120
	before switch id 140539650623120
	('id ', 140539650623120)
	after get id  4
	before switch id 140539650623120
	('id ', 140539650623120)
	after get id  5
	before switch id 140539650623120

I am wondering why there is two continus line "before switch id 140539650623120",  I think I already del the old coroutine. It seem after del the coroutine , the func body can continue exec. If the new coroutine can work , why it can't get the id 3 ?

**Comment by snaury** [comment]
That happens because after you change `entry_fun_cortione` to point to the new greenlet it continues to execute. On the next cycle you print id of the new greenlet and switch to main, then main switches to the new greenlet, which starts executing and prints its id.

If you want to print id of the current greenlet you should use `id(greenlet.getcurrent())`.

**Comment by jiamo** [comment]
How about the id 3,  in func main it switch(3), but in entry_fun it lost.

**Comment by snaury** [comment]
When you switch for the first time switch arguments go to function arguments, so your `id 3` should be in `test`.
