### ISSUE TITLE
Crashes on ppc32

### ISSUE THREAD

**Issue by snaury** [python-greenlet/greenlet#94]
@awilfox experiences crashes on ppc32 with gcc-4.8.4. I suspect this might be due to tampering with gpr30 (frame pointer) which is used as a general purpose register when frames are omitted and gets damaged by the increment. Need to find a way to save/restore it separately, similar to other architectures. So far `lwz` instruction looks promising, but I might have to resort to `mr` and hope the variable doesn't stay in a register.

**Comment by awilfox** [comment]
Here we go: https://gist.github.com/awilfox/4fdf96a51663b177c0a3

I hope this helps.

**Comment by snaury** [comment]
Ok, I see now that the problem is not with gpr30 (it's used for relative addressing, recalculated on every entry point from lr and saving/restoring it would be useless). However in the broken version compiler decides to use gpr31 as a saved copy of gpr1 and later uses it to restore the frame. Please see if https://github.com/snaury/greenlet/tree/wip-ppc32 would fix the problem.

**Comment by awilfox** [comment]
No joy :(

```
awilcox@vixey ~/greenlet [wip-ppc32] $ python3.4 setup.py build
running build
running build_ext
building 'greenlet' extension
creating build
creating build/temp.linux-ppc-3.4
powerpc-apple-linux-gnu-gcc -pthread -fPIC -I/usr/include/python3.4 -c greenlet.c -o build/temp.linux-ppc-3.4/greenlet.o
In file included from slp_platformselect.h:18:0,
                 from greenlet.c:328:
platform/switch_ppc_linux.h: In function ‘slp_switch’:
platform/switch_ppc_linux.h:68:1: error: 31 cannot be used in asm here
 }
 ^
platform/switch_ppc_linux.h:68:1: error: 31 cannot be used in asm here
error: command 'powerpc-apple-linux-gnu-gcc' failed with exit status 1
```

**Comment by snaury** [comment]
Thanks, of course the register is protected, no way around that. Unfortunately I can't think of any way to save and restore it, and I'm not familiar with the platform to even attempt something crazy like indirect calls to helper functions. The only possible way I see so far is to force compiling without optimisations, like some other architectures. Could you please check if compiling with `-Os` works and what is the result of `platform.machine()`?

**Comment by awilfox** [comment]
I am so sorry for the delay.  My laptop had a hardware failure, and I had a move.

Yes, ``-Os`` works perfectly.

```
>>> platform.machine()
'ppc'
>>> sys.platform
'linux'
>>> os.uname()
posix.uname_result(sysname='Linux', nodename='vixey', release='3.17.0-vixey', version='#2 PREEMPT Tue Oct 7 23:00:37 CDT 2014', machine='ppc')
```

**Comment by snaury** [comment]
I've added a workaround in master.

**Comment by jamadden** [comment]
Closing as this is believed fixed in https://github.com/python-greenlet/greenlet/commit/7352e9fab517838683d492362b3c6d1cba49a1b8
