### ISSUE TITLE
want to understand the magic slp_switch assemble code

### ISSUE THREAD

**Issue by pengfei-xue** [python-greenlet/greenlet#95]
is there any doc about these slp_switch funcs? especially for the assemble code?

**Comment by sonthonaxrk** [comment]
Greenlet works by changing the frame of the stack when you call switch.  Computer programs have a pointer to their current stack called the stack pointer; this is usually implemented in hardware as a register.  Changing the value of the stack pointer to the value of another frame will take you to that frame.  This appears magical as it’s a super unsafe function directly manipulating memory that the C language is unable to access, so assembly language is needed to sidestep this limitation.

https://en.wikipedia.org/wiki/Coroutine#Implementations_for_C

It looks strange and it’s dangerous,

**Comment by pengfei-xue** [comment]
> Greenlet works by changing the frame of the stack when you call switch. Computer programs have a pointer to their current stack called the stack pointer; this is usually implemented in hardware as a register. Changing the value of the stack pointer to the value of another frame will take you to that frame. This appears magical as it’s a super unsafe function directly manipulating memory that the C language is unable to access, so assembly language is needed to sidestep this limitation.
> 
> https://en.wikipedia.org/wiki/Coroutine#Implementations_for_C
> 
> It looks strange and it’s dangerous, but it’s a fairly common pattern.

thanks for the reply, i have waited for 5 years 💯
