### ISSUE TITLE
Missing Python 3.5 in PyPI classifier

### ISSUE THREAD

**Issue by nicoddemus** [python-greenlet/greenlet#97]
The [pypi for greenlet](https://pypi.python.org/pypi/greenlet) page is missing the `Programming Language :: Python :: 3.5` classifier.

**Comment by snaury** [comment]
Unfortunately greenlet 0.4.9 was released before Python 3.5, but `setup.py` in the repository has 3.5 classifier, and I have released Windows binaries for 3.5 since then, not sure what can be done without making another release. There are not enough changes for making a new release yet.

**Comment by snaury** [comment]
Seems like it's possible to edit that, added it on PyPI.

**Comment by nicoddemus** [comment]
Thanks. :smile:

You can also use:

'''
python setup.py register
'''

To update pypi with the current contents of setup.py. :grin:
