### ISSUE TITLE
greenlet.h:8:20: fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by zzxwill** [python-greenlet/greenlet#99]
I tried to install greenlet by 'pip install greenlet'. It failed due to 'gcc not found'.
**1. Should you regard gcc as a dependency of greenlet?
**
After gcc is installed, greenlet failed to the following error message.

**2. "The easiest way to get Greenlet is to install it with pip or easy_install: pip install greenlet" This seems not enough to have greenlet installed. Please help check the issue below. Thanks.
**

[root@host-10-0-0-61 ~]# pip install greenlet
Collecting greenlet
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached greenlet-0.4.9.tar.gz
Building wheels for collected packages: greenlet
  Running setup.py bdist_wheel for greenlet ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZiqkMe/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpVW8A3Zpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'greenlet' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
  In file included from greenlet.c:5:0:
  greenlet.h:8:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
Installing collected packages: greenlet
  Running setup.py install for greenlet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZiqkMe/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8xzoG8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
    In file included from greenlet.c:5:0:
    greenlet.h:8:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZiqkMe/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8xzoG8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ZiqkMe/greenlet

**Comment by saghul** [comment]
You need to have the python development package installed, which contains the header files. On Debian / Ubuntu systems it's called python-dev.

**Comment by zzxwill** [comment]
You are correct!
While I have to google myself for the issue and then find out we need to install python-dev[el]. Why doesn't greenlet include python-dev as an requirement? Thanks.

**Comment by saghul** [comment]
Because python-dev is not a Python package you can download from PyPI, it's peovided by your distro of choice or you installed Python manually.

**Comment by zzxwill** [comment]
So all python developer should know at the very beginning 'python.h' comes from package python-dev? Is there a way to indicate the fact? Thanks.

**Comment by snaury** [comment]
Sorry, but this bug report is invalid. There's no dependency on gcc in greenlet, it doesn't depend on any specific Linux package like python-dev either. Being a cross platform python extension module what it needs is a working Python installation that can build extension modules. Usually Python uses the same compiler that was used to build itself, e.g. Visual Studio on Windows, gcc on Linux, clang on OSX, etc.

You probably need to learn more about your Linux distribution, read documentation and ask questions on support forums first.
